version: "3.8"
services: 
  backend:
    build:
      context: .
      dockerfile: Dockerfile # 
    ports:
      - 8001:5000 #플라스크는 5000번 포트 
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:5.7.2
    restart: always
    environment: 
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - .dbdata:/var/lib/mysql
    ports: 
      - 33067:3306 